export const X_KILOCODE_VERSION = "X-AxonCode-Version"
export const X_KILOCODE_ORGANIZATIONID = "X-KiloCode-OrganizationId"
export const X_KILOCODE_TASKID = "X-AxonCode-TaskId"
export const X_KILOCODE_PROJECTID = "X-KiloCode-ProjectId"
export const X_KILOCODE_TESTER = "X-KILOCODE-TESTER"
